server:
  port: 8080

spring:
  profiles: api-gateway
  main:
    allow-bean-definition-overriding: true

  data:
    mongodb:
      uri: mongodb://root:test@localhost:27017/food?authSource=admin

  cloud:
    eureka:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka

    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
        - id: menu-service
          uri: lb://MENU-SERVICE
          predicates:
            - Path=/menu/**
          filters:
            - AddRequestHeader=Authorization, Bearer #{jwt.token}
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
          filters:
            - AddRequestHeader=Authorization, Bearer #{jwt.token}
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**
          filters:
            - AddRequestHeader=Authorization, Bearer #{jwt.token}

logging:
  level:
    org.springframework.security: DEBUG

jwt:
  secret: "AkilanNilavanEduthavainathamChennaiTamilNadu"
  expiration-time: 86400000
