spring:
  data:
    mongodb:
      uri: mongodb://root:test@localhost:27017/food?authSource=admin

  cloud:
    eureka:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka
